print("It's a test of escape sequences")
print("This is backslash '\\\\' \\ ")
print("This is single-quote '\\\'' \'")
print("This is double-quote '\\\"' \"")
print("This is bell '\\a' \a")
print("This is backspace '\\b' \b")
print("This is formfeed '\\f' \f")
print("This is carriage '\\r' \r")
print("\tThis is tab '\\t' \t")
print("\vThis is vertical tab '\\v' \v")
print("Test")
